version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./postgres_prod:/var/lib/postgresql/data
    env_file:
      - ./.db_env
  web:
    build: .
    command: gunicorn replserver.wsgi:application --bind 0.0.0.0:80
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db