version: "3.9"
   
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    restart: "on-failure"
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.db_env
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "./wait-for-it.sh db:5432 -- python manage.py makemigrations &&
                      python manage.py migrate &&
                      gunicorn replserver.wsgi:application --bind 0.0.0.0:8000"
    env_file: .env
    expose:
      - "80"
    depends_on:
      - db