version: "3.9"
   
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/staticfiles
    restart: "on-failure"
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.db_env
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn replserver.wsgi:application --bind 0.0.0.0:8000
    env_file: .env
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - static_volume:/home/app/staticfiles

volumes:
  static_volume: