# Generated by Django 3.2.9 on 2021-11-06 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repl_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='REPLHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('executed_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='REPLSessionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='REPLSession',
        ),
        migrations.AddField(
            model_name='replhistoryentry',
            name='session_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='repl_app.replsessioninfo'),
        ),
    ]
