# Generated by Django 3.2.9 on 2021-11-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repl_app', '0002_auto_20211106_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
