# Generated by Django 3.2.9 on 2021-11-09 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repl_app', '0003_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='replsessioninfo',
            name='device_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='repl_app.devicetoken'),
        ),
    ]
