# Generated by Django 3.2.9 on 2021-11-09 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repl_app', '0004_replsessioninfo_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replsessioninfo',
            name='device_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='repl_app.devicetoken'),
        ),
    ]
